name: Branch Name Check

on:
  pull_request:
    types: [opened, edited]
    branches: [ "dev" ]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check branch name
        id: check_branch_name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          EXEMPT_BRANCH="release"
          VALID_TYPES=("feat" "hotfix" "fix" "chore" "refactor" "test")
          IS_VALID=false

          # Check if the branch is exempt
          if [[ "$BRANCH_NAME" == "$EXEMPT_BRANCH/"* ]]; then
            echo "Branch is exempt from naming rules."
            echo "::set-output name=invalid::false"
            exit 0
          fi

          # Check if the branch name matches the required pattern
          for type in "${VALID_TYPES[@]}"; do
            if [[ "$BRANCH_NAME" =~ ^$type/CSN-[0-9]+- ]]; then
              IS_VALID=true
              break
            fi
          done

          if [ "$IS_VALID" = false ]; then
            echo "❌ ERROR: Branch name '$BRANCH_NAME' is invalid - Must include a JIRA ticket like 'CSN-xxxx' (e.g., CSN-1234, CSN-98765)"
            echo "👉 Branch name should follow the format: '<prefix>/CSN-XXXX-description'"
            echo "::set-output name=invalid::true"
          else
            echo "Valid branch name"
            echo "::set-output name=invalid::false"
          fi

      - name: Fail the check for invalid branch name
        if: steps.check_branch_name.outputs.invalid == 'true'
        run: |
          echo "❌ Exiting with failure due to invalid branch name"
          exit 1